# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prot.game.cutscene_pb2 as game_dot_cutscene__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/cutscene_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CutsceneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlayedCutscenes = channel.unary_unary(
                '/ck.game.CutsceneService/RegisterPlayedCutscenes',
                request_serializer=game_dot_cutscene__pb2.RegisterPlayedCutscenesRequest.SerializeToString,
                response_deserializer=game_dot_cutscene__pb2.RegisterPlayedCutscenesResponse.FromString,
                _registered_method=True)
        self.CompleteTutorials = channel.unary_unary(
                '/ck.game.CutsceneService/CompleteTutorials',
                request_serializer=game_dot_cutscene__pb2.CompleteTutorialsRequest.SerializeToString,
                response_deserializer=game_dot_cutscene__pb2.CompleteTutorialsResponse.FromString,
                _registered_method=True)
        self.RegisterContentUnlockPopUps = channel.unary_unary(
                '/ck.game.CutsceneService/RegisterContentUnlockPopUps',
                request_serializer=game_dot_cutscene__pb2.RegisterContentUnlockPopUpsRequest.SerializeToString,
                response_deserializer=game_dot_cutscene__pb2.RegisterContentUnlockPopUpsResponse.FromString,
                _registered_method=True)
        self.UnlockSeasonableRecords = channel.unary_unary(
                '/ck.game.CutsceneService/UnlockSeasonableRecords',
                request_serializer=game_dot_cutscene__pb2.UnlockSeasonableRecordsRequest.SerializeToString,
                response_deserializer=game_dot_cutscene__pb2.UnlockSeasonableRecordsResponse.FromString,
                _registered_method=True)


class CutsceneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPlayedCutscenes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTutorials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterContentUnlockPopUps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockSeasonableRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CutsceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlayedCutscenes': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlayedCutscenes,
                    request_deserializer=game_dot_cutscene__pb2.RegisterPlayedCutscenesRequest.FromString,
                    response_serializer=game_dot_cutscene__pb2.RegisterPlayedCutscenesResponse.SerializeToString,
            ),
            'CompleteTutorials': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTutorials,
                    request_deserializer=game_dot_cutscene__pb2.CompleteTutorialsRequest.FromString,
                    response_serializer=game_dot_cutscene__pb2.CompleteTutorialsResponse.SerializeToString,
            ),
            'RegisterContentUnlockPopUps': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterContentUnlockPopUps,
                    request_deserializer=game_dot_cutscene__pb2.RegisterContentUnlockPopUpsRequest.FromString,
                    response_serializer=game_dot_cutscene__pb2.RegisterContentUnlockPopUpsResponse.SerializeToString,
            ),
            'UnlockSeasonableRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockSeasonableRecords,
                    request_deserializer=game_dot_cutscene__pb2.UnlockSeasonableRecordsRequest.FromString,
                    response_serializer=game_dot_cutscene__pb2.UnlockSeasonableRecordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ck.game.CutsceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ck.game.CutsceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CutsceneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPlayedCutscenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.CutsceneService/RegisterPlayedCutscenes',
            game_dot_cutscene__pb2.RegisterPlayedCutscenesRequest.SerializeToString,
            game_dot_cutscene__pb2.RegisterPlayedCutscenesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTutorials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.CutsceneService/CompleteTutorials',
            game_dot_cutscene__pb2.CompleteTutorialsRequest.SerializeToString,
            game_dot_cutscene__pb2.CompleteTutorialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterContentUnlockPopUps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.CutsceneService/RegisterContentUnlockPopUps',
            game_dot_cutscene__pb2.RegisterContentUnlockPopUpsRequest.SerializeToString,
            game_dot_cutscene__pb2.RegisterContentUnlockPopUpsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockSeasonableRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.CutsceneService/UnlockSeasonableRecords',
            game_dot_cutscene__pb2.UnlockSeasonableRecordsRequest.SerializeToString,
            game_dot_cutscene__pb2.UnlockSeasonableRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
