# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prot.game.shop_pb2 as game_dot_shop__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHistories = channel.unary_unary(
                '/ck.game.ShopService/GetHistories',
                request_serializer=game_dot_shop__pb2.GetHistoriesRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.GetHistoriesResponse.FromString,
                _registered_method=True)
        self.PurchaseSummon = channel.unary_unary(
                '/ck.game.ShopService/PurchaseSummon',
                request_serializer=game_dot_shop__pb2.PurchaseSummonRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseSummonResponse.FromString,
                _registered_method=True)
        self.UpdateItemShop = channel.unary_unary(
                '/ck.game.ShopService/UpdateItemShop',
                request_serializer=game_dot_shop__pb2.UpdateItemShopRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.UpdateItemShopResponse.FromString,
                _registered_method=True)
        self.ResetItemShopManually = channel.unary_unary(
                '/ck.game.ShopService/ResetItemShopManually',
                request_serializer=game_dot_shop__pb2.ResetItemShopManuallyRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ResetItemShopManuallyResponse.FromString,
                _registered_method=True)
        self.PurchaseItemShopSlot = channel.unary_unary(
                '/ck.game.ShopService/PurchaseItemShopSlot',
                request_serializer=game_dot_shop__pb2.PurchaseItemShopSlotRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseItemShopSlotResponse.FromString,
                _registered_method=True)
        self.PurchaseMileageItem = channel.unary_unary(
                '/ck.game.ShopService/PurchaseMileageItem',
                request_serializer=game_dot_shop__pb2.PurchaseMileageItemRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseMileageItemResponse.FromString,
                _registered_method=True)
        self.PurchasePackage = channel.unary_unary(
                '/ck.game.ShopService/PurchasePackage',
                request_serializer=game_dot_shop__pb2.PurchasePackageRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchasePackageResponse.FromString,
                _registered_method=True)
        self.RegisterShownPackagePopup = channel.unary_unary(
                '/ck.game.ShopService/RegisterShownPackagePopup',
                request_serializer=game_dot_shop__pb2.RegisterShownPackagePopupRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.RegisterShownPackagePopupResponse.FromString,
                _registered_method=True)
        self.ClearPackageMission = channel.unary_unary(
                '/ck.game.ShopService/ClearPackageMission',
                request_serializer=game_dot_shop__pb2.ClearPackageMissionRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ClearPackageMissionResponse.FromString,
                _registered_method=True)
        self.ClearPackageMissionsGroups = channel.unary_unary(
                '/ck.game.ShopService/ClearPackageMissionsGroups',
                request_serializer=game_dot_shop__pb2.ClearPackageMissionsGroupsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ClearPackageMissionsGroupsResponse.FromString,
                _registered_method=True)
        self.ReceivePackageBonus = channel.unary_unary(
                '/ck.game.ShopService/ReceivePackageBonus',
                request_serializer=game_dot_shop__pb2.ReceivePackageBonusRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceivePackageBonusResponse.FromString,
                _registered_method=True)
        self.ReceiveAccumulatedBonus = channel.unary_unary(
                '/ck.game.ShopService/ReceiveAccumulatedBonus',
                request_serializer=game_dot_shop__pb2.ReceiveAccumulatedBonusRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceiveAccumulatedBonusResponse.FromString,
                _registered_method=True)
        self.PurchaseInsufficientItems = channel.unary_unary(
                '/ck.game.ShopService/PurchaseInsufficientItems',
                request_serializer=game_dot_shop__pb2.PurchaseInsufficientItemsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseInsufficientItemsResponse.FromString,
                _registered_method=True)
        self.ChargeItem = channel.unary_unary(
                '/ck.game.ShopService/ChargeItem',
                request_serializer=game_dot_shop__pb2.ChargeItemRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ChargeItemResponse.FromString,
                _registered_method=True)
        self.PurchaseCurrency = channel.unary_unary(
                '/ck.game.ShopService/PurchaseCurrency',
                request_serializer=game_dot_shop__pb2.PurchaseCurrencyRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseCurrencyResponse.FromString,
                _registered_method=True)
        self.PurchaseFlat = channel.unary_unary(
                '/ck.game.ShopService/PurchaseFlat',
                request_serializer=game_dot_shop__pb2.PurchaseFlatRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseFlatResponse.FromString,
                _registered_method=True)
        self.ReceiveFlatDailyRewards = channel.unary_unary(
                '/ck.game.ShopService/ReceiveFlatDailyRewards',
                request_serializer=game_dot_shop__pb2.ReceiveFlatDailyRewardsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceiveFlatDailyRewardsResponse.FromString,
                _registered_method=True)
        self.PurchaseKingdomPass = channel.unary_unary(
                '/ck.game.ShopService/PurchaseKingdomPass',
                request_serializer=game_dot_shop__pb2.PurchaseKingdomPassRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.PurchaseKingdomPassResponse.FromString,
                _registered_method=True)
        self.CompleteStructureTheme = channel.unary_unary(
                '/ck.game.ShopService/CompleteStructureTheme',
                request_serializer=game_dot_shop__pb2.CompleteStructureThemeRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.CompleteStructureThemeResponse.FromString,
                _registered_method=True)
        self.UnlockTile = channel.unary_unary(
                '/ck.game.ShopService/UnlockTile',
                request_serializer=game_dot_shop__pb2.UnlockTileRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.UnlockTileResponse.FromString,
                _registered_method=True)
        self.UnlockStructureSkin = channel.unary_unary(
                '/ck.game.ShopService/UnlockStructureSkin',
                request_serializer=game_dot_shop__pb2.UnlockStructureSkinRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.UnlockStructureSkinResponse.FromString,
                _registered_method=True)
        self.UnlockTownBackgroundSkin = channel.unary_unary(
                '/ck.game.ShopService/UnlockTownBackgroundSkin',
                request_serializer=game_dot_shop__pb2.UnlockTownBackgroundSkinRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.UnlockTownBackgroundSkinResponse.FromString,
                _registered_method=True)
        self.ReceiveAllExternalStoreUnrelatedRewards = channel.unary_unary(
                '/ck.game.ShopService/ReceiveAllExternalStoreUnrelatedRewards',
                request_serializer=game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsResponse.FromString,
                _registered_method=True)
        self.ReceiveExternalStoreRelatedReward = channel.unary_unary(
                '/ck.game.ShopService/ReceiveExternalStoreRelatedReward',
                request_serializer=game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardResponse.FromString,
                _registered_method=True)
        self.VerifyBillingInfo = channel.unary_unary(
                '/ck.game.ShopService/VerifyBillingInfo',
                request_serializer=game_dot_shop__pb2.VerifyBillingInfoRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.VerifyBillingInfoResponse.FromString,
                _registered_method=True)
        self.ExchangeItem = channel.unary_unary(
                '/ck.game.ShopService/ExchangeItem',
                request_serializer=game_dot_shop__pb2.ExchangeItemRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ExchangeItemResponse.FromString,
                _registered_method=True)
        self.RewardSelectableBox = channel.unary_unary(
                '/ck.game.ShopService/RewardSelectableBox',
                request_serializer=game_dot_shop__pb2.RewardSelectableBoxRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.RewardSelectableBoxResponse.FromString,
                _registered_method=True)
        self.GetRewardBoxRates = channel.unary_unary(
                '/ck.game.ShopService/GetRewardBoxRates',
                request_serializer=game_dot_shop__pb2.GetRewardBoxRatesRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.GetRewardBoxRatesResponse.FromString,
                _registered_method=True)
        self.GetUserSummonRates = channel.unary_unary(
                '/ck.game.ShopService/GetUserSummonRates',
                request_serializer=game_dot_shop__pb2.GetUserSummonRatesRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.GetUserSummonRatesResponse.FromString,
                _registered_method=True)
        self.UpdateGachaPickupGroups = channel.unary_unary(
                '/ck.game.ShopService/UpdateGachaPickupGroups',
                request_serializer=game_dot_shop__pb2.UpdateGachaPickupGroupsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.UpdateGachaPickupGroupsResponse.FromString,
                _registered_method=True)
        self.ExchangeItemsToAcorn = channel.unary_unary(
                '/ck.game.ShopService/ExchangeItemsToAcorn',
                request_serializer=game_dot_shop__pb2.ExchangeItemsToAcornRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ExchangeItemsToAcornResponse.FromString,
                _registered_method=True)
        self.CloseItemShop = channel.unary_unary(
                '/ck.game.ShopService/CloseItemShop',
                request_serializer=game_dot_shop__pb2.CloseItemShopRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.CloseItemShopResponse.FromString,
                _registered_method=True)
        self.OpenUsableRandomRewardBox = channel.unary_unary(
                '/ck.game.ShopService/OpenUsableRandomRewardBox',
                request_serializer=game_dot_shop__pb2.OpenUsableRandomRewardBoxRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.OpenUsableRandomRewardBoxResponse.FromString,
                _registered_method=True)
        self.ReceiveGachaStepRewards = channel.unary_unary(
                '/ck.game.ShopService/ReceiveGachaStepRewards',
                request_serializer=game_dot_shop__pb2.ReceiveGachaStepRewardsRequest.SerializeToString,
                response_deserializer=game_dot_shop__pb2.ReceiveGachaStepRewardsResponse.FromString,
                _registered_method=True)


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHistories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseSummon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetItemShopManually(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseItemShopSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseMileageItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchasePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterShownPackagePopup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearPackageMission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearPackageMissionsGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceivePackageBonus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveAccumulatedBonus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseInsufficientItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChargeItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseCurrency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseFlat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveFlatDailyRewards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseKingdomPass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteStructureTheme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockTile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockStructureSkin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockTownBackgroundSkin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveAllExternalStoreUnrelatedRewards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveExternalStoreRelatedReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBillingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RewardSelectableBox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRewardBoxRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSummonRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGachaPickupGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeItemsToAcorn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseItemShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenUsableRandomRewardBox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveGachaStepRewards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHistories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistories,
                    request_deserializer=game_dot_shop__pb2.GetHistoriesRequest.FromString,
                    response_serializer=game_dot_shop__pb2.GetHistoriesResponse.SerializeToString,
            ),
            'PurchaseSummon': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseSummon,
                    request_deserializer=game_dot_shop__pb2.PurchaseSummonRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseSummonResponse.SerializeToString,
            ),
            'UpdateItemShop': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemShop,
                    request_deserializer=game_dot_shop__pb2.UpdateItemShopRequest.FromString,
                    response_serializer=game_dot_shop__pb2.UpdateItemShopResponse.SerializeToString,
            ),
            'ResetItemShopManually': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetItemShopManually,
                    request_deserializer=game_dot_shop__pb2.ResetItemShopManuallyRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ResetItemShopManuallyResponse.SerializeToString,
            ),
            'PurchaseItemShopSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseItemShopSlot,
                    request_deserializer=game_dot_shop__pb2.PurchaseItemShopSlotRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseItemShopSlotResponse.SerializeToString,
            ),
            'PurchaseMileageItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseMileageItem,
                    request_deserializer=game_dot_shop__pb2.PurchaseMileageItemRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseMileageItemResponse.SerializeToString,
            ),
            'PurchasePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchasePackage,
                    request_deserializer=game_dot_shop__pb2.PurchasePackageRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchasePackageResponse.SerializeToString,
            ),
            'RegisterShownPackagePopup': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterShownPackagePopup,
                    request_deserializer=game_dot_shop__pb2.RegisterShownPackagePopupRequest.FromString,
                    response_serializer=game_dot_shop__pb2.RegisterShownPackagePopupResponse.SerializeToString,
            ),
            'ClearPackageMission': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearPackageMission,
                    request_deserializer=game_dot_shop__pb2.ClearPackageMissionRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ClearPackageMissionResponse.SerializeToString,
            ),
            'ClearPackageMissionsGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearPackageMissionsGroups,
                    request_deserializer=game_dot_shop__pb2.ClearPackageMissionsGroupsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ClearPackageMissionsGroupsResponse.SerializeToString,
            ),
            'ReceivePackageBonus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceivePackageBonus,
                    request_deserializer=game_dot_shop__pb2.ReceivePackageBonusRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceivePackageBonusResponse.SerializeToString,
            ),
            'ReceiveAccumulatedBonus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveAccumulatedBonus,
                    request_deserializer=game_dot_shop__pb2.ReceiveAccumulatedBonusRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceiveAccumulatedBonusResponse.SerializeToString,
            ),
            'PurchaseInsufficientItems': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseInsufficientItems,
                    request_deserializer=game_dot_shop__pb2.PurchaseInsufficientItemsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseInsufficientItemsResponse.SerializeToString,
            ),
            'ChargeItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ChargeItem,
                    request_deserializer=game_dot_shop__pb2.ChargeItemRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ChargeItemResponse.SerializeToString,
            ),
            'PurchaseCurrency': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseCurrency,
                    request_deserializer=game_dot_shop__pb2.PurchaseCurrencyRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseCurrencyResponse.SerializeToString,
            ),
            'PurchaseFlat': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseFlat,
                    request_deserializer=game_dot_shop__pb2.PurchaseFlatRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseFlatResponse.SerializeToString,
            ),
            'ReceiveFlatDailyRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveFlatDailyRewards,
                    request_deserializer=game_dot_shop__pb2.ReceiveFlatDailyRewardsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceiveFlatDailyRewardsResponse.SerializeToString,
            ),
            'PurchaseKingdomPass': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseKingdomPass,
                    request_deserializer=game_dot_shop__pb2.PurchaseKingdomPassRequest.FromString,
                    response_serializer=game_dot_shop__pb2.PurchaseKingdomPassResponse.SerializeToString,
            ),
            'CompleteStructureTheme': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteStructureTheme,
                    request_deserializer=game_dot_shop__pb2.CompleteStructureThemeRequest.FromString,
                    response_serializer=game_dot_shop__pb2.CompleteStructureThemeResponse.SerializeToString,
            ),
            'UnlockTile': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockTile,
                    request_deserializer=game_dot_shop__pb2.UnlockTileRequest.FromString,
                    response_serializer=game_dot_shop__pb2.UnlockTileResponse.SerializeToString,
            ),
            'UnlockStructureSkin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockStructureSkin,
                    request_deserializer=game_dot_shop__pb2.UnlockStructureSkinRequest.FromString,
                    response_serializer=game_dot_shop__pb2.UnlockStructureSkinResponse.SerializeToString,
            ),
            'UnlockTownBackgroundSkin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockTownBackgroundSkin,
                    request_deserializer=game_dot_shop__pb2.UnlockTownBackgroundSkinRequest.FromString,
                    response_serializer=game_dot_shop__pb2.UnlockTownBackgroundSkinResponse.SerializeToString,
            ),
            'ReceiveAllExternalStoreUnrelatedRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveAllExternalStoreUnrelatedRewards,
                    request_deserializer=game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsResponse.SerializeToString,
            ),
            'ReceiveExternalStoreRelatedReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveExternalStoreRelatedReward,
                    request_deserializer=game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardResponse.SerializeToString,
            ),
            'VerifyBillingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBillingInfo,
                    request_deserializer=game_dot_shop__pb2.VerifyBillingInfoRequest.FromString,
                    response_serializer=game_dot_shop__pb2.VerifyBillingInfoResponse.SerializeToString,
            ),
            'ExchangeItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeItem,
                    request_deserializer=game_dot_shop__pb2.ExchangeItemRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ExchangeItemResponse.SerializeToString,
            ),
            'RewardSelectableBox': grpc.unary_unary_rpc_method_handler(
                    servicer.RewardSelectableBox,
                    request_deserializer=game_dot_shop__pb2.RewardSelectableBoxRequest.FromString,
                    response_serializer=game_dot_shop__pb2.RewardSelectableBoxResponse.SerializeToString,
            ),
            'GetRewardBoxRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRewardBoxRates,
                    request_deserializer=game_dot_shop__pb2.GetRewardBoxRatesRequest.FromString,
                    response_serializer=game_dot_shop__pb2.GetRewardBoxRatesResponse.SerializeToString,
            ),
            'GetUserSummonRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSummonRates,
                    request_deserializer=game_dot_shop__pb2.GetUserSummonRatesRequest.FromString,
                    response_serializer=game_dot_shop__pb2.GetUserSummonRatesResponse.SerializeToString,
            ),
            'UpdateGachaPickupGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGachaPickupGroups,
                    request_deserializer=game_dot_shop__pb2.UpdateGachaPickupGroupsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.UpdateGachaPickupGroupsResponse.SerializeToString,
            ),
            'ExchangeItemsToAcorn': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeItemsToAcorn,
                    request_deserializer=game_dot_shop__pb2.ExchangeItemsToAcornRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ExchangeItemsToAcornResponse.SerializeToString,
            ),
            'CloseItemShop': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseItemShop,
                    request_deserializer=game_dot_shop__pb2.CloseItemShopRequest.FromString,
                    response_serializer=game_dot_shop__pb2.CloseItemShopResponse.SerializeToString,
            ),
            'OpenUsableRandomRewardBox': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenUsableRandomRewardBox,
                    request_deserializer=game_dot_shop__pb2.OpenUsableRandomRewardBoxRequest.FromString,
                    response_serializer=game_dot_shop__pb2.OpenUsableRandomRewardBoxResponse.SerializeToString,
            ),
            'ReceiveGachaStepRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveGachaStepRewards,
                    request_deserializer=game_dot_shop__pb2.ReceiveGachaStepRewardsRequest.FromString,
                    response_serializer=game_dot_shop__pb2.ReceiveGachaStepRewardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ck.game.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ck.game.ShopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHistories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/GetHistories',
            game_dot_shop__pb2.GetHistoriesRequest.SerializeToString,
            game_dot_shop__pb2.GetHistoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseSummon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseSummon',
            game_dot_shop__pb2.PurchaseSummonRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseSummonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/UpdateItemShop',
            game_dot_shop__pb2.UpdateItemShopRequest.SerializeToString,
            game_dot_shop__pb2.UpdateItemShopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetItemShopManually(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ResetItemShopManually',
            game_dot_shop__pb2.ResetItemShopManuallyRequest.SerializeToString,
            game_dot_shop__pb2.ResetItemShopManuallyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseItemShopSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseItemShopSlot',
            game_dot_shop__pb2.PurchaseItemShopSlotRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseItemShopSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseMileageItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseMileageItem',
            game_dot_shop__pb2.PurchaseMileageItemRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseMileageItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchasePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchasePackage',
            game_dot_shop__pb2.PurchasePackageRequest.SerializeToString,
            game_dot_shop__pb2.PurchasePackageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterShownPackagePopup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/RegisterShownPackagePopup',
            game_dot_shop__pb2.RegisterShownPackagePopupRequest.SerializeToString,
            game_dot_shop__pb2.RegisterShownPackagePopupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearPackageMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ClearPackageMission',
            game_dot_shop__pb2.ClearPackageMissionRequest.SerializeToString,
            game_dot_shop__pb2.ClearPackageMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearPackageMissionsGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ClearPackageMissionsGroups',
            game_dot_shop__pb2.ClearPackageMissionsGroupsRequest.SerializeToString,
            game_dot_shop__pb2.ClearPackageMissionsGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceivePackageBonus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceivePackageBonus',
            game_dot_shop__pb2.ReceivePackageBonusRequest.SerializeToString,
            game_dot_shop__pb2.ReceivePackageBonusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveAccumulatedBonus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceiveAccumulatedBonus',
            game_dot_shop__pb2.ReceiveAccumulatedBonusRequest.SerializeToString,
            game_dot_shop__pb2.ReceiveAccumulatedBonusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseInsufficientItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseInsufficientItems',
            game_dot_shop__pb2.PurchaseInsufficientItemsRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseInsufficientItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChargeItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ChargeItem',
            game_dot_shop__pb2.ChargeItemRequest.SerializeToString,
            game_dot_shop__pb2.ChargeItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseCurrency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseCurrency',
            game_dot_shop__pb2.PurchaseCurrencyRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseCurrencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseFlat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseFlat',
            game_dot_shop__pb2.PurchaseFlatRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseFlatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveFlatDailyRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceiveFlatDailyRewards',
            game_dot_shop__pb2.ReceiveFlatDailyRewardsRequest.SerializeToString,
            game_dot_shop__pb2.ReceiveFlatDailyRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseKingdomPass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/PurchaseKingdomPass',
            game_dot_shop__pb2.PurchaseKingdomPassRequest.SerializeToString,
            game_dot_shop__pb2.PurchaseKingdomPassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteStructureTheme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/CompleteStructureTheme',
            game_dot_shop__pb2.CompleteStructureThemeRequest.SerializeToString,
            game_dot_shop__pb2.CompleteStructureThemeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/UnlockTile',
            game_dot_shop__pb2.UnlockTileRequest.SerializeToString,
            game_dot_shop__pb2.UnlockTileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockStructureSkin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/UnlockStructureSkin',
            game_dot_shop__pb2.UnlockStructureSkinRequest.SerializeToString,
            game_dot_shop__pb2.UnlockStructureSkinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockTownBackgroundSkin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/UnlockTownBackgroundSkin',
            game_dot_shop__pb2.UnlockTownBackgroundSkinRequest.SerializeToString,
            game_dot_shop__pb2.UnlockTownBackgroundSkinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveAllExternalStoreUnrelatedRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceiveAllExternalStoreUnrelatedRewards',
            game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsRequest.SerializeToString,
            game_dot_shop__pb2.ReceiveAllExternalStoreUnrelatedRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveExternalStoreRelatedReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceiveExternalStoreRelatedReward',
            game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardRequest.SerializeToString,
            game_dot_shop__pb2.ReceiveExternalStoreRelatedRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBillingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/VerifyBillingInfo',
            game_dot_shop__pb2.VerifyBillingInfoRequest.SerializeToString,
            game_dot_shop__pb2.VerifyBillingInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ExchangeItem',
            game_dot_shop__pb2.ExchangeItemRequest.SerializeToString,
            game_dot_shop__pb2.ExchangeItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RewardSelectableBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/RewardSelectableBox',
            game_dot_shop__pb2.RewardSelectableBoxRequest.SerializeToString,
            game_dot_shop__pb2.RewardSelectableBoxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRewardBoxRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/GetRewardBoxRates',
            game_dot_shop__pb2.GetRewardBoxRatesRequest.SerializeToString,
            game_dot_shop__pb2.GetRewardBoxRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSummonRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/GetUserSummonRates',
            game_dot_shop__pb2.GetUserSummonRatesRequest.SerializeToString,
            game_dot_shop__pb2.GetUserSummonRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGachaPickupGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/UpdateGachaPickupGroups',
            game_dot_shop__pb2.UpdateGachaPickupGroupsRequest.SerializeToString,
            game_dot_shop__pb2.UpdateGachaPickupGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeItemsToAcorn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ExchangeItemsToAcorn',
            game_dot_shop__pb2.ExchangeItemsToAcornRequest.SerializeToString,
            game_dot_shop__pb2.ExchangeItemsToAcornResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseItemShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/CloseItemShop',
            game_dot_shop__pb2.CloseItemShopRequest.SerializeToString,
            game_dot_shop__pb2.CloseItemShopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenUsableRandomRewardBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/OpenUsableRandomRewardBox',
            game_dot_shop__pb2.OpenUsableRandomRewardBoxRequest.SerializeToString,
            game_dot_shop__pb2.OpenUsableRandomRewardBoxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveGachaStepRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.ShopService/ReceiveGachaStepRewards',
            game_dot_shop__pb2.ReceiveGachaStepRewardsRequest.SerializeToString,
            game_dot_shop__pb2.ReceiveGachaStepRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
