# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prot.game.social_pb2 as game_dot_social__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/social_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SocialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSocialState = channel.unary_unary(
                '/ck.game.SocialService/GetSocialState',
                request_serializer=game_dot_social__pb2.GetSocialStateRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetSocialStateResponse.FromString,
                _registered_method=True)
        self.SearchUsers = channel.unary_unary(
                '/ck.game.SocialService/SearchUsers',
                request_serializer=game_dot_social__pb2.SearchUsersRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SearchUsersResponse.FromString,
                _registered_method=True)
        self.GetRecommendedFriends = channel.unary_unary(
                '/ck.game.SocialService/GetRecommendedFriends',
                request_serializer=game_dot_social__pb2.GetRecommendedFriendsRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetRecommendedFriendsResponse.FromString,
                _registered_method=True)
        self.GetUserSummary = channel.unary_unary(
                '/ck.game.SocialService/GetUserSummary',
                request_serializer=game_dot_social__pb2.GetUserSummaryRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetUserSummaryResponse.FromString,
                _registered_method=True)
        self.GetUserSummaries = channel.unary_unary(
                '/ck.game.SocialService/GetUserSummaries',
                request_serializer=game_dot_social__pb2.GetUserSummariesRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetUserSummariesResponse.FromString,
                _registered_method=True)
        self.GetSocialSummary = channel.unary_unary(
                '/ck.game.SocialService/GetSocialSummary',
                request_serializer=game_dot_social__pb2.GetSocialSummaryRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetSocialSummaryResponse.FromString,
                _registered_method=True)
        self.GetSocialSummaries = channel.unary_unary(
                '/ck.game.SocialService/GetSocialSummaries',
                request_serializer=game_dot_social__pb2.GetSocialSummariesRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetSocialSummariesResponse.FromString,
                _registered_method=True)
        self.GetFriendProfile = channel.unary_unary(
                '/ck.game.SocialService/GetFriendProfile',
                request_serializer=game_dot_social__pb2.GetFriendProfileRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetFriendProfileResponse.FromString,
                _registered_method=True)
        self.AddFriend = channel.unary_unary(
                '/ck.game.SocialService/AddFriend',
                request_serializer=game_dot_social__pb2.AddFriendRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.AddFriendResponse.FromString,
                _registered_method=True)
        self.DeleteFriend = channel.unary_unary(
                '/ck.game.SocialService/DeleteFriend',
                request_serializer=game_dot_social__pb2.DeleteFriendRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.DeleteFriendResponse.FromString,
                _registered_method=True)
        self.CancelFriendRequest = channel.unary_unary(
                '/ck.game.SocialService/CancelFriendRequest',
                request_serializer=game_dot_social__pb2.CancelFriendRequestRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.CancelFriendRequestResponse.FromString,
                _registered_method=True)
        self.AcceptFriendRequest = channel.unary_unary(
                '/ck.game.SocialService/AcceptFriendRequest',
                request_serializer=game_dot_social__pb2.AcceptFriendRequestRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.AcceptFriendRequestResponse.FromString,
                _registered_method=True)
        self.RejectFriendRequest = channel.unary_unary(
                '/ck.game.SocialService/RejectFriendRequest',
                request_serializer=game_dot_social__pb2.RejectFriendRequestRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.RejectFriendRequestResponse.FromString,
                _registered_method=True)
        self.GetFriendKingdom = channel.unary_unary(
                '/ck.game.SocialService/GetFriendKingdom',
                request_serializer=game_dot_social__pb2.GetFriendKingdomRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetFriendKingdomResponse.FromString,
                _registered_method=True)
        self.SendLike = channel.unary_unary(
                '/ck.game.SocialService/SendLike',
                request_serializer=game_dot_social__pb2.SendLikeRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendLikeResponse.FromString,
                _registered_method=True)
        self.SendDailyRandomGift = channel.unary_unary(
                '/ck.game.SocialService/SendDailyRandomGift',
                request_serializer=game_dot_social__pb2.SendDailyRandomGiftRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendDailyRandomGiftResponse.FromString,
                _registered_method=True)
        self.SendDailyRandomGifts = channel.unary_unary(
                '/ck.game.SocialService/SendDailyRandomGifts',
                request_serializer=game_dot_social__pb2.SendDailyRandomGiftsRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendDailyRandomGiftsResponse.FromString,
                _registered_method=True)
        self.SendSpecialRandomGift = channel.unary_unary(
                '/ck.game.SocialService/SendSpecialRandomGift',
                request_serializer=game_dot_social__pb2.SendSpecialRandomGiftRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendSpecialRandomGiftResponse.FromString,
                _registered_method=True)
        self.SendPopularityGift = channel.unary_unary(
                '/ck.game.SocialService/SendPopularityGift',
                request_serializer=game_dot_social__pb2.SendPopularityGiftRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendPopularityGiftResponse.FromString,
                _registered_method=True)
        self.GetPopularityContributionRanking = channel.unary_unary(
                '/ck.game.SocialService/GetPopularityContributionRanking',
                request_serializer=game_dot_social__pb2.GetPopularityContributionRankingRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetPopularityContributionRankingResponse.FromString,
                _registered_method=True)
        self.GetPopularityTopRanking = channel.unary_unary(
                '/ck.game.SocialService/GetPopularityTopRanking',
                request_serializer=game_dot_social__pb2.GetPopularityTopRankingRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetPopularityTopRankingResponse.FromString,
                _registered_method=True)
        self.GetFriendlyPvpMatchInfo = channel.unary_unary(
                '/ck.game.SocialService/GetFriendlyPvpMatchInfo',
                request_serializer=game_dot_social__pb2.GetFriendlyPvpMatchInfoRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetFriendlyPvpMatchInfoResponse.FromString,
                _registered_method=True)
        self.SendFriendlyPvpMatchResult = channel.unary_unary(
                '/ck.game.SocialService/SendFriendlyPvpMatchResult',
                request_serializer=game_dot_social__pb2.SendFriendlyPvpMatchResultRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.SendFriendlyPvpMatchResultResponse.FromString,
                _registered_method=True)
        self.ChangeUserVisibilityInPopularityContributionRanking = channel.unary_unary(
                '/ck.game.SocialService/ChangeUserVisibilityInPopularityContributionRanking',
                request_serializer=game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingResponse.FromString,
                _registered_method=True)
        self.ChangeOnlyFriendsCanSendGifts = channel.unary_unary(
                '/ck.game.SocialService/ChangeOnlyFriendsCanSendGifts',
                request_serializer=game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsResponse.FromString,
                _registered_method=True)
        self.GetSocialSummariesWithPvpRating = channel.unary_unary(
                '/ck.game.SocialService/GetSocialSummariesWithPvpRating',
                request_serializer=game_dot_social__pb2.GetSocialSummariesWithPvpRatingRequest.SerializeToString,
                response_deserializer=game_dot_social__pb2.GetSocialSummariesWithPvpRatingResponse.FromString,
                _registered_method=True)


class SocialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSocialState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendedFriends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocialSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocialSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendKingdom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDailyRandomGift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDailyRandomGifts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSpecialRandomGift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPopularityGift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPopularityContributionRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPopularityTopRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendlyPvpMatchInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFriendlyPvpMatchResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeUserVisibilityInPopularityContributionRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeOnlyFriendsCanSendGifts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocialSummariesWithPvpRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSocialState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialState,
                    request_deserializer=game_dot_social__pb2.GetSocialStateRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetSocialStateResponse.SerializeToString,
            ),
            'SearchUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsers,
                    request_deserializer=game_dot_social__pb2.SearchUsersRequest.FromString,
                    response_serializer=game_dot_social__pb2.SearchUsersResponse.SerializeToString,
            ),
            'GetRecommendedFriends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendedFriends,
                    request_deserializer=game_dot_social__pb2.GetRecommendedFriendsRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetRecommendedFriendsResponse.SerializeToString,
            ),
            'GetUserSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSummary,
                    request_deserializer=game_dot_social__pb2.GetUserSummaryRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetUserSummaryResponse.SerializeToString,
            ),
            'GetUserSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSummaries,
                    request_deserializer=game_dot_social__pb2.GetUserSummariesRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetUserSummariesResponse.SerializeToString,
            ),
            'GetSocialSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialSummary,
                    request_deserializer=game_dot_social__pb2.GetSocialSummaryRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetSocialSummaryResponse.SerializeToString,
            ),
            'GetSocialSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialSummaries,
                    request_deserializer=game_dot_social__pb2.GetSocialSummariesRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetSocialSummariesResponse.SerializeToString,
            ),
            'GetFriendProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendProfile,
                    request_deserializer=game_dot_social__pb2.GetFriendProfileRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetFriendProfileResponse.SerializeToString,
            ),
            'AddFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFriend,
                    request_deserializer=game_dot_social__pb2.AddFriendRequest.FromString,
                    response_serializer=game_dot_social__pb2.AddFriendResponse.SerializeToString,
            ),
            'DeleteFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFriend,
                    request_deserializer=game_dot_social__pb2.DeleteFriendRequest.FromString,
                    response_serializer=game_dot_social__pb2.DeleteFriendResponse.SerializeToString,
            ),
            'CancelFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelFriendRequest,
                    request_deserializer=game_dot_social__pb2.CancelFriendRequestRequest.FromString,
                    response_serializer=game_dot_social__pb2.CancelFriendRequestResponse.SerializeToString,
            ),
            'AcceptFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptFriendRequest,
                    request_deserializer=game_dot_social__pb2.AcceptFriendRequestRequest.FromString,
                    response_serializer=game_dot_social__pb2.AcceptFriendRequestResponse.SerializeToString,
            ),
            'RejectFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectFriendRequest,
                    request_deserializer=game_dot_social__pb2.RejectFriendRequestRequest.FromString,
                    response_serializer=game_dot_social__pb2.RejectFriendRequestResponse.SerializeToString,
            ),
            'GetFriendKingdom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendKingdom,
                    request_deserializer=game_dot_social__pb2.GetFriendKingdomRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetFriendKingdomResponse.SerializeToString,
            ),
            'SendLike': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLike,
                    request_deserializer=game_dot_social__pb2.SendLikeRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendLikeResponse.SerializeToString,
            ),
            'SendDailyRandomGift': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDailyRandomGift,
                    request_deserializer=game_dot_social__pb2.SendDailyRandomGiftRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendDailyRandomGiftResponse.SerializeToString,
            ),
            'SendDailyRandomGifts': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDailyRandomGifts,
                    request_deserializer=game_dot_social__pb2.SendDailyRandomGiftsRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendDailyRandomGiftsResponse.SerializeToString,
            ),
            'SendSpecialRandomGift': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSpecialRandomGift,
                    request_deserializer=game_dot_social__pb2.SendSpecialRandomGiftRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendSpecialRandomGiftResponse.SerializeToString,
            ),
            'SendPopularityGift': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPopularityGift,
                    request_deserializer=game_dot_social__pb2.SendPopularityGiftRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendPopularityGiftResponse.SerializeToString,
            ),
            'GetPopularityContributionRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPopularityContributionRanking,
                    request_deserializer=game_dot_social__pb2.GetPopularityContributionRankingRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetPopularityContributionRankingResponse.SerializeToString,
            ),
            'GetPopularityTopRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPopularityTopRanking,
                    request_deserializer=game_dot_social__pb2.GetPopularityTopRankingRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetPopularityTopRankingResponse.SerializeToString,
            ),
            'GetFriendlyPvpMatchInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendlyPvpMatchInfo,
                    request_deserializer=game_dot_social__pb2.GetFriendlyPvpMatchInfoRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetFriendlyPvpMatchInfoResponse.SerializeToString,
            ),
            'SendFriendlyPvpMatchResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFriendlyPvpMatchResult,
                    request_deserializer=game_dot_social__pb2.SendFriendlyPvpMatchResultRequest.FromString,
                    response_serializer=game_dot_social__pb2.SendFriendlyPvpMatchResultResponse.SerializeToString,
            ),
            'ChangeUserVisibilityInPopularityContributionRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeUserVisibilityInPopularityContributionRanking,
                    request_deserializer=game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingRequest.FromString,
                    response_serializer=game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingResponse.SerializeToString,
            ),
            'ChangeOnlyFriendsCanSendGifts': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeOnlyFriendsCanSendGifts,
                    request_deserializer=game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsRequest.FromString,
                    response_serializer=game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsResponse.SerializeToString,
            ),
            'GetSocialSummariesWithPvpRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialSummariesWithPvpRating,
                    request_deserializer=game_dot_social__pb2.GetSocialSummariesWithPvpRatingRequest.FromString,
                    response_serializer=game_dot_social__pb2.GetSocialSummariesWithPvpRatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ck.game.SocialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ck.game.SocialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SocialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSocialState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetSocialState',
            game_dot_social__pb2.GetSocialStateRequest.SerializeToString,
            game_dot_social__pb2.GetSocialStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SearchUsers',
            game_dot_social__pb2.SearchUsersRequest.SerializeToString,
            game_dot_social__pb2.SearchUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendedFriends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetRecommendedFriends',
            game_dot_social__pb2.GetRecommendedFriendsRequest.SerializeToString,
            game_dot_social__pb2.GetRecommendedFriendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetUserSummary',
            game_dot_social__pb2.GetUserSummaryRequest.SerializeToString,
            game_dot_social__pb2.GetUserSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetUserSummaries',
            game_dot_social__pb2.GetUserSummariesRequest.SerializeToString,
            game_dot_social__pb2.GetUserSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSocialSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetSocialSummary',
            game_dot_social__pb2.GetSocialSummaryRequest.SerializeToString,
            game_dot_social__pb2.GetSocialSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSocialSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetSocialSummaries',
            game_dot_social__pb2.GetSocialSummariesRequest.SerializeToString,
            game_dot_social__pb2.GetSocialSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFriendProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetFriendProfile',
            game_dot_social__pb2.GetFriendProfileRequest.SerializeToString,
            game_dot_social__pb2.GetFriendProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/AddFriend',
            game_dot_social__pb2.AddFriendRequest.SerializeToString,
            game_dot_social__pb2.AddFriendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/DeleteFriend',
            game_dot_social__pb2.DeleteFriendRequest.SerializeToString,
            game_dot_social__pb2.DeleteFriendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/CancelFriendRequest',
            game_dot_social__pb2.CancelFriendRequestRequest.SerializeToString,
            game_dot_social__pb2.CancelFriendRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/AcceptFriendRequest',
            game_dot_social__pb2.AcceptFriendRequestRequest.SerializeToString,
            game_dot_social__pb2.AcceptFriendRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/RejectFriendRequest',
            game_dot_social__pb2.RejectFriendRequestRequest.SerializeToString,
            game_dot_social__pb2.RejectFriendRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFriendKingdom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetFriendKingdom',
            game_dot_social__pb2.GetFriendKingdomRequest.SerializeToString,
            game_dot_social__pb2.GetFriendKingdomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendLike',
            game_dot_social__pb2.SendLikeRequest.SerializeToString,
            game_dot_social__pb2.SendLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDailyRandomGift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendDailyRandomGift',
            game_dot_social__pb2.SendDailyRandomGiftRequest.SerializeToString,
            game_dot_social__pb2.SendDailyRandomGiftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDailyRandomGifts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendDailyRandomGifts',
            game_dot_social__pb2.SendDailyRandomGiftsRequest.SerializeToString,
            game_dot_social__pb2.SendDailyRandomGiftsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSpecialRandomGift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendSpecialRandomGift',
            game_dot_social__pb2.SendSpecialRandomGiftRequest.SerializeToString,
            game_dot_social__pb2.SendSpecialRandomGiftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPopularityGift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendPopularityGift',
            game_dot_social__pb2.SendPopularityGiftRequest.SerializeToString,
            game_dot_social__pb2.SendPopularityGiftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPopularityContributionRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetPopularityContributionRanking',
            game_dot_social__pb2.GetPopularityContributionRankingRequest.SerializeToString,
            game_dot_social__pb2.GetPopularityContributionRankingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPopularityTopRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetPopularityTopRanking',
            game_dot_social__pb2.GetPopularityTopRankingRequest.SerializeToString,
            game_dot_social__pb2.GetPopularityTopRankingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFriendlyPvpMatchInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetFriendlyPvpMatchInfo',
            game_dot_social__pb2.GetFriendlyPvpMatchInfoRequest.SerializeToString,
            game_dot_social__pb2.GetFriendlyPvpMatchInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFriendlyPvpMatchResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/SendFriendlyPvpMatchResult',
            game_dot_social__pb2.SendFriendlyPvpMatchResultRequest.SerializeToString,
            game_dot_social__pb2.SendFriendlyPvpMatchResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeUserVisibilityInPopularityContributionRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/ChangeUserVisibilityInPopularityContributionRanking',
            game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingRequest.SerializeToString,
            game_dot_social__pb2.ChangeUserVisibilityInPopularityContributionRankingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeOnlyFriendsCanSendGifts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/ChangeOnlyFriendsCanSendGifts',
            game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsRequest.SerializeToString,
            game_dot_social__pb2.ChangeOnlyFriendsCanSendGiftsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSocialSummariesWithPvpRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.SocialService/GetSocialSummariesWithPvpRating',
            game_dot_social__pb2.GetSocialSummariesWithPvpRatingRequest.SerializeToString,
            game_dot_social__pb2.GetSocialSummariesWithPvpRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
