# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prot.game.story_adventure_pb2 as game_dot_story__adventure__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/story_adventure_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoryAdventureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStoryAdventureEpisodeInfo = channel.unary_unary(
                '/ck.game.StoryAdventureService/UpdateStoryAdventureEpisodeInfo',
                request_serializer=game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoResponse.FromString,
                _registered_method=True)
        self.ClearStoryAdventureMission = channel.unary_unary(
                '/ck.game.StoryAdventureService/ClearStoryAdventureMission',
                request_serializer=game_dot_story__adventure__pb2.ClearStoryAdventureMissionRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.ClearStoryAdventureMissionResponse.FromString,
                _registered_method=True)
        self.StartStoryAdventureTask = channel.unary_unary(
                '/ck.game.StoryAdventureService/StartStoryAdventureTask',
                request_serializer=game_dot_story__adventure__pb2.StartStoryAdventureTaskRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.StartStoryAdventureTaskResponse.FromString,
                _registered_method=True)
        self.CompleteStoryAdventureTask = channel.unary_unary(
                '/ck.game.StoryAdventureService/CompleteStoryAdventureTask',
                request_serializer=game_dot_story__adventure__pb2.CompleteStoryAdventureTaskRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.CompleteStoryAdventureTaskResponse.FromString,
                _registered_method=True)
        self.MoveStoryAdventureEpisode = channel.unary_unary(
                '/ck.game.StoryAdventureService/MoveStoryAdventureEpisode',
                request_serializer=game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeResponse.FromString,
                _registered_method=True)
        self.ReceiveStoryAdventureProgressReward = channel.unary_unary(
                '/ck.game.StoryAdventureService/ReceiveStoryAdventureProgressReward',
                request_serializer=game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardResponse.FromString,
                _registered_method=True)
        self.CancelStoryAdventureTask = channel.unary_unary(
                '/ck.game.StoryAdventureService/CancelStoryAdventureTask',
                request_serializer=game_dot_story__adventure__pb2.CancelStoryAdventureTaskRequest.SerializeToString,
                response_deserializer=game_dot_story__adventure__pb2.CancelStoryAdventureTaskResponse.FromString,
                _registered_method=True)


class StoryAdventureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateStoryAdventureEpisodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearStoryAdventureMission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStoryAdventureTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteStoryAdventureTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveStoryAdventureEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveStoryAdventureProgressReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelStoryAdventureTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoryAdventureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateStoryAdventureEpisodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStoryAdventureEpisodeInfo,
                    request_deserializer=game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoResponse.SerializeToString,
            ),
            'ClearStoryAdventureMission': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearStoryAdventureMission,
                    request_deserializer=game_dot_story__adventure__pb2.ClearStoryAdventureMissionRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.ClearStoryAdventureMissionResponse.SerializeToString,
            ),
            'StartStoryAdventureTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStoryAdventureTask,
                    request_deserializer=game_dot_story__adventure__pb2.StartStoryAdventureTaskRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.StartStoryAdventureTaskResponse.SerializeToString,
            ),
            'CompleteStoryAdventureTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteStoryAdventureTask,
                    request_deserializer=game_dot_story__adventure__pb2.CompleteStoryAdventureTaskRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.CompleteStoryAdventureTaskResponse.SerializeToString,
            ),
            'MoveStoryAdventureEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveStoryAdventureEpisode,
                    request_deserializer=game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeResponse.SerializeToString,
            ),
            'ReceiveStoryAdventureProgressReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveStoryAdventureProgressReward,
                    request_deserializer=game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardResponse.SerializeToString,
            ),
            'CancelStoryAdventureTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelStoryAdventureTask,
                    request_deserializer=game_dot_story__adventure__pb2.CancelStoryAdventureTaskRequest.FromString,
                    response_serializer=game_dot_story__adventure__pb2.CancelStoryAdventureTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ck.game.StoryAdventureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ck.game.StoryAdventureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoryAdventureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateStoryAdventureEpisodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/UpdateStoryAdventureEpisodeInfo',
            game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoRequest.SerializeToString,
            game_dot_story__adventure__pb2.UpdateStoryAdventureEpisodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearStoryAdventureMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/ClearStoryAdventureMission',
            game_dot_story__adventure__pb2.ClearStoryAdventureMissionRequest.SerializeToString,
            game_dot_story__adventure__pb2.ClearStoryAdventureMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStoryAdventureTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/StartStoryAdventureTask',
            game_dot_story__adventure__pb2.StartStoryAdventureTaskRequest.SerializeToString,
            game_dot_story__adventure__pb2.StartStoryAdventureTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteStoryAdventureTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/CompleteStoryAdventureTask',
            game_dot_story__adventure__pb2.CompleteStoryAdventureTaskRequest.SerializeToString,
            game_dot_story__adventure__pb2.CompleteStoryAdventureTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveStoryAdventureEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/MoveStoryAdventureEpisode',
            game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeRequest.SerializeToString,
            game_dot_story__adventure__pb2.MoveStoryAdventureEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveStoryAdventureProgressReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/ReceiveStoryAdventureProgressReward',
            game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardRequest.SerializeToString,
            game_dot_story__adventure__pb2.ReceiveStoryAdventureProgressRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelStoryAdventureTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.StoryAdventureService/CancelStoryAdventureTask',
            game_dot_story__adventure__pb2.CancelStoryAdventureTaskRequest.SerializeToString,
            game_dot_story__adventure__pb2.CancelStoryAdventureTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
