# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game/time.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'game/time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import prot.common_entities_pb2 as common__entities__pb2
import prot.game.entities_pb2 as game_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgame/time.proto\x12\x07\x63k.game\x1a\x15\x63ommon_entities.proto\x1a\x13game/entities.proto\"\x14\n\x12GetDateTimeRequest\"2\n\x13GetDateTimeResponse\x12\x1b\n\tdate_time\x18\x01 \x01(\x0b\x32\x08.ck.Time2W\n\x0bTimeService\x12H\n\x0bGetDateTime\x12\x1b.ck.game.GetDateTimeRequest\x1a\x1c.ck.game.GetDateTimeResponseBC\n(com.devsisters.ck.services.game.protobuf\xaa\x02\x16Services.Game.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game.time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.devsisters.ck.services.game.protobuf\252\002\026Services.Game.Protobuf'
  _globals['_GETDATETIMEREQUEST']._serialized_start=72
  _globals['_GETDATETIMEREQUEST']._serialized_end=92
  _globals['_GETDATETIMERESPONSE']._serialized_start=94
  _globals['_GETDATETIMERESPONSE']._serialized_end=144
  _globals['_TIMESERVICE']._serialized_start=146
  _globals['_TIMESERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
