# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prot.game.town_pb2 as game_dot_town__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game/town_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TownServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApproveConstruction = channel.unary_unary(
                '/ck.game.TownService/ApproveConstruction',
                request_serializer=game_dot_town__pb2.ApproveConstructionRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ApproveConstructionResponse.FromString,
                _registered_method=True)
        self.InstantCompleteConstruction = channel.unary_unary(
                '/ck.game.TownService/InstantCompleteConstruction',
                request_serializer=game_dot_town__pb2.InstantCompleteConstructionRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.InstantCompleteConstructionResponse.FromString,
                _registered_method=True)
        self.AccelerateConstruction = channel.unary_unary(
                '/ck.game.TownService/AccelerateConstruction',
                request_serializer=game_dot_town__pb2.AccelerateConstructionRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.AccelerateConstructionResponse.FromString,
                _registered_method=True)
        self.ExpandCraftQueue = channel.unary_unary(
                '/ck.game.TownService/ExpandCraftQueue',
                request_serializer=game_dot_town__pb2.ExpandCraftQueueRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ExpandCraftQueueResponse.FromString,
                _registered_method=True)
        self.LevelUpStructure = channel.unary_unary(
                '/ck.game.TownService/LevelUpStructure',
                request_serializer=game_dot_town__pb2.LevelUpStructureRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.LevelUpStructureResponse.FromString,
                _registered_method=True)
        self.SupplyConstructionMaterials = channel.unary_unary(
                '/ck.game.TownService/SupplyConstructionMaterials',
                request_serializer=game_dot_town__pb2.SupplyConstructionMaterialsRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.SupplyConstructionMaterialsResponse.FromString,
                _registered_method=True)
        self.DemolishStructure = channel.unary_unary(
                '/ck.game.TownService/DemolishStructure',
                request_serializer=game_dot_town__pb2.DemolishStructureRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.DemolishStructureResponse.FromString,
                _registered_method=True)
        self.EditTown = channel.unary_unary(
                '/ck.game.TownService/EditTown',
                request_serializer=game_dot_town__pb2.EditTownRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.EditTownResponse.FromString,
                _registered_method=True)
        self.StartTownSegmentUnlock = channel.unary_unary(
                '/ck.game.TownService/StartTownSegmentUnlock',
                request_serializer=game_dot_town__pb2.StartTownSegmentUnlockRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.StartTownSegmentUnlockResponse.FromString,
                _registered_method=True)
        self.FinishTownSegmentUnlock = channel.unary_unary(
                '/ck.game.TownService/FinishTownSegmentUnlock',
                request_serializer=game_dot_town__pb2.FinishTownSegmentUnlockRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.FinishTownSegmentUnlockResponse.FromString,
                _registered_method=True)
        self.InstantCompleteTownSegmentUnlock = channel.unary_unary(
                '/ck.game.TownService/InstantCompleteTownSegmentUnlock',
                request_serializer=game_dot_town__pb2.InstantCompleteTownSegmentUnlockRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.InstantCompleteTownSegmentUnlockResponse.FromString,
                _registered_method=True)
        self.AccelerateTownSegmentUnlock = channel.unary_unary(
                '/ck.game.TownService/AccelerateTownSegmentUnlock',
                request_serializer=game_dot_town__pb2.AccelerateTownSegmentUnlockRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.AccelerateTownSegmentUnlockResponse.FromString,
                _registered_method=True)
        self.UnlockBattleTownSegment = channel.unary_unary(
                '/ck.game.TownService/UnlockBattleTownSegment',
                request_serializer=game_dot_town__pb2.UnlockBattleTownSegmentRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.UnlockBattleTownSegmentResponse.FromString,
                _registered_method=True)
        self.ReceiveCumulativeAutoProductionsReward = channel.unary_unary(
                '/ck.game.TownService/ReceiveCumulativeAutoProductionsReward',
                request_serializer=game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardResponse.FromString,
                _registered_method=True)
        self.RefreshFountainProductionReward = channel.unary_unary(
                '/ck.game.TownService/RefreshFountainProductionReward',
                request_serializer=game_dot_town__pb2.RefreshFountainProductionRewardRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.RefreshFountainProductionRewardResponse.FromString,
                _registered_method=True)
        self.ReceiveFountainProductionReward = channel.unary_unary(
                '/ck.game.TownService/ReceiveFountainProductionReward',
                request_serializer=game_dot_town__pb2.ReceiveFountainProductionRewardRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ReceiveFountainProductionRewardResponse.FromString,
                _registered_method=True)
        self.ReceiveLandmarkProductionReward = channel.unary_unary(
                '/ck.game.TownService/ReceiveLandmarkProductionReward',
                request_serializer=game_dot_town__pb2.ReceiveLandmarkProductionRewardRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ReceiveLandmarkProductionRewardResponse.FromString,
                _registered_method=True)
        self.ChangeAutoProductionCanActivate = channel.unary_unary(
                '/ck.game.TownService/ChangeAutoProductionCanActivate',
                request_serializer=game_dot_town__pb2.ChangeAutoProductionCanActivateRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ChangeAutoProductionCanActivateResponse.FromString,
                _registered_method=True)
        self.SaveTownPreset = channel.unary_unary(
                '/ck.game.TownService/SaveTownPreset',
                request_serializer=game_dot_town__pb2.SaveTownPresetRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.SaveTownPresetResponse.FromString,
                _registered_method=True)
        self.LoadTownPreset = channel.unary_unary(
                '/ck.game.TownService/LoadTownPreset',
                request_serializer=game_dot_town__pb2.LoadTownPresetRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.LoadTownPresetResponse.FromString,
                _registered_method=True)
        self.RenameTownPreset = channel.unary_unary(
                '/ck.game.TownService/RenameTownPreset',
                request_serializer=game_dot_town__pb2.RenameTownPresetRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.RenameTownPresetResponse.FromString,
                _registered_method=True)
        self.DeleteTownPreset = channel.unary_unary(
                '/ck.game.TownService/DeleteTownPreset',
                request_serializer=game_dot_town__pb2.DeleteTownPresetRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.DeleteTownPresetResponse.FromString,
                _registered_method=True)
        self.ClearTown = channel.unary_unary(
                '/ck.game.TownService/ClearTown',
                request_serializer=game_dot_town__pb2.ClearTownRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.ClearTownResponse.FromString,
                _registered_method=True)
        self.UpgradeTownPresetStorage = channel.unary_unary(
                '/ck.game.TownService/UpgradeTownPresetStorage',
                request_serializer=game_dot_town__pb2.UpgradeTownPresetStorageRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.UpgradeTownPresetStorageResponse.FromString,
                _registered_method=True)
        self.SetStructureBookmarked = channel.unary_unary(
                '/ck.game.TownService/SetStructureBookmarked',
                request_serializer=game_dot_town__pb2.SetStructureBookmarkedRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.SetStructureBookmarkedResponse.FromString,
                _registered_method=True)
        self.SetHouseIdsBookmarked = channel.unary_unary(
                '/ck.game.TownService/SetHouseIdsBookmarked',
                request_serializer=game_dot_town__pb2.SetHouseIdsBookmarkedRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.SetHouseIdsBookmarkedResponse.FromString,
                _registered_method=True)
        self.UnlockSkyGardenIsland = channel.unary_unary(
                '/ck.game.TownService/UnlockSkyGardenIsland',
                request_serializer=game_dot_town__pb2.UnlockSkyGardenIslandRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.UnlockSkyGardenIslandResponse.FromString,
                _registered_method=True)
        self.GetTownPreset = channel.unary_unary(
                '/ck.game.TownService/GetTownPreset',
                request_serializer=game_dot_town__pb2.GetTownPresetRequest.SerializeToString,
                response_deserializer=game_dot_town__pb2.GetTownPresetResponse.FromString,
                _registered_method=True)


class TownServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApproveConstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstantCompleteConstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccelerateConstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCraftQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LevelUpStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SupplyConstructionMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemolishStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTownSegmentUnlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishTownSegmentUnlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstantCompleteTownSegmentUnlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccelerateTownSegmentUnlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockBattleTownSegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveCumulativeAutoProductionsReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshFountainProductionReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveFountainProductionReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveLandmarkProductionReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAutoProductionCanActivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveTownPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadTownPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameTownPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTownPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearTown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpgradeTownPresetStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStructureBookmarked(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHouseIdsBookmarked(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockSkyGardenIsland(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTownPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApproveConstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveConstruction,
                    request_deserializer=game_dot_town__pb2.ApproveConstructionRequest.FromString,
                    response_serializer=game_dot_town__pb2.ApproveConstructionResponse.SerializeToString,
            ),
            'InstantCompleteConstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.InstantCompleteConstruction,
                    request_deserializer=game_dot_town__pb2.InstantCompleteConstructionRequest.FromString,
                    response_serializer=game_dot_town__pb2.InstantCompleteConstructionResponse.SerializeToString,
            ),
            'AccelerateConstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.AccelerateConstruction,
                    request_deserializer=game_dot_town__pb2.AccelerateConstructionRequest.FromString,
                    response_serializer=game_dot_town__pb2.AccelerateConstructionResponse.SerializeToString,
            ),
            'ExpandCraftQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCraftQueue,
                    request_deserializer=game_dot_town__pb2.ExpandCraftQueueRequest.FromString,
                    response_serializer=game_dot_town__pb2.ExpandCraftQueueResponse.SerializeToString,
            ),
            'LevelUpStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.LevelUpStructure,
                    request_deserializer=game_dot_town__pb2.LevelUpStructureRequest.FromString,
                    response_serializer=game_dot_town__pb2.LevelUpStructureResponse.SerializeToString,
            ),
            'SupplyConstructionMaterials': grpc.unary_unary_rpc_method_handler(
                    servicer.SupplyConstructionMaterials,
                    request_deserializer=game_dot_town__pb2.SupplyConstructionMaterialsRequest.FromString,
                    response_serializer=game_dot_town__pb2.SupplyConstructionMaterialsResponse.SerializeToString,
            ),
            'DemolishStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.DemolishStructure,
                    request_deserializer=game_dot_town__pb2.DemolishStructureRequest.FromString,
                    response_serializer=game_dot_town__pb2.DemolishStructureResponse.SerializeToString,
            ),
            'EditTown': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTown,
                    request_deserializer=game_dot_town__pb2.EditTownRequest.FromString,
                    response_serializer=game_dot_town__pb2.EditTownResponse.SerializeToString,
            ),
            'StartTownSegmentUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTownSegmentUnlock,
                    request_deserializer=game_dot_town__pb2.StartTownSegmentUnlockRequest.FromString,
                    response_serializer=game_dot_town__pb2.StartTownSegmentUnlockResponse.SerializeToString,
            ),
            'FinishTownSegmentUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishTownSegmentUnlock,
                    request_deserializer=game_dot_town__pb2.FinishTownSegmentUnlockRequest.FromString,
                    response_serializer=game_dot_town__pb2.FinishTownSegmentUnlockResponse.SerializeToString,
            ),
            'InstantCompleteTownSegmentUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.InstantCompleteTownSegmentUnlock,
                    request_deserializer=game_dot_town__pb2.InstantCompleteTownSegmentUnlockRequest.FromString,
                    response_serializer=game_dot_town__pb2.InstantCompleteTownSegmentUnlockResponse.SerializeToString,
            ),
            'AccelerateTownSegmentUnlock': grpc.unary_unary_rpc_method_handler(
                    servicer.AccelerateTownSegmentUnlock,
                    request_deserializer=game_dot_town__pb2.AccelerateTownSegmentUnlockRequest.FromString,
                    response_serializer=game_dot_town__pb2.AccelerateTownSegmentUnlockResponse.SerializeToString,
            ),
            'UnlockBattleTownSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockBattleTownSegment,
                    request_deserializer=game_dot_town__pb2.UnlockBattleTownSegmentRequest.FromString,
                    response_serializer=game_dot_town__pb2.UnlockBattleTownSegmentResponse.SerializeToString,
            ),
            'ReceiveCumulativeAutoProductionsReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCumulativeAutoProductionsReward,
                    request_deserializer=game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardRequest.FromString,
                    response_serializer=game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardResponse.SerializeToString,
            ),
            'RefreshFountainProductionReward': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshFountainProductionReward,
                    request_deserializer=game_dot_town__pb2.RefreshFountainProductionRewardRequest.FromString,
                    response_serializer=game_dot_town__pb2.RefreshFountainProductionRewardResponse.SerializeToString,
            ),
            'ReceiveFountainProductionReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveFountainProductionReward,
                    request_deserializer=game_dot_town__pb2.ReceiveFountainProductionRewardRequest.FromString,
                    response_serializer=game_dot_town__pb2.ReceiveFountainProductionRewardResponse.SerializeToString,
            ),
            'ReceiveLandmarkProductionReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveLandmarkProductionReward,
                    request_deserializer=game_dot_town__pb2.ReceiveLandmarkProductionRewardRequest.FromString,
                    response_serializer=game_dot_town__pb2.ReceiveLandmarkProductionRewardResponse.SerializeToString,
            ),
            'ChangeAutoProductionCanActivate': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAutoProductionCanActivate,
                    request_deserializer=game_dot_town__pb2.ChangeAutoProductionCanActivateRequest.FromString,
                    response_serializer=game_dot_town__pb2.ChangeAutoProductionCanActivateResponse.SerializeToString,
            ),
            'SaveTownPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTownPreset,
                    request_deserializer=game_dot_town__pb2.SaveTownPresetRequest.FromString,
                    response_serializer=game_dot_town__pb2.SaveTownPresetResponse.SerializeToString,
            ),
            'LoadTownPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadTownPreset,
                    request_deserializer=game_dot_town__pb2.LoadTownPresetRequest.FromString,
                    response_serializer=game_dot_town__pb2.LoadTownPresetResponse.SerializeToString,
            ),
            'RenameTownPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameTownPreset,
                    request_deserializer=game_dot_town__pb2.RenameTownPresetRequest.FromString,
                    response_serializer=game_dot_town__pb2.RenameTownPresetResponse.SerializeToString,
            ),
            'DeleteTownPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTownPreset,
                    request_deserializer=game_dot_town__pb2.DeleteTownPresetRequest.FromString,
                    response_serializer=game_dot_town__pb2.DeleteTownPresetResponse.SerializeToString,
            ),
            'ClearTown': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTown,
                    request_deserializer=game_dot_town__pb2.ClearTownRequest.FromString,
                    response_serializer=game_dot_town__pb2.ClearTownResponse.SerializeToString,
            ),
            'UpgradeTownPresetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpgradeTownPresetStorage,
                    request_deserializer=game_dot_town__pb2.UpgradeTownPresetStorageRequest.FromString,
                    response_serializer=game_dot_town__pb2.UpgradeTownPresetStorageResponse.SerializeToString,
            ),
            'SetStructureBookmarked': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStructureBookmarked,
                    request_deserializer=game_dot_town__pb2.SetStructureBookmarkedRequest.FromString,
                    response_serializer=game_dot_town__pb2.SetStructureBookmarkedResponse.SerializeToString,
            ),
            'SetHouseIdsBookmarked': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHouseIdsBookmarked,
                    request_deserializer=game_dot_town__pb2.SetHouseIdsBookmarkedRequest.FromString,
                    response_serializer=game_dot_town__pb2.SetHouseIdsBookmarkedResponse.SerializeToString,
            ),
            'UnlockSkyGardenIsland': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockSkyGardenIsland,
                    request_deserializer=game_dot_town__pb2.UnlockSkyGardenIslandRequest.FromString,
                    response_serializer=game_dot_town__pb2.UnlockSkyGardenIslandResponse.SerializeToString,
            ),
            'GetTownPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTownPreset,
                    request_deserializer=game_dot_town__pb2.GetTownPresetRequest.FromString,
                    response_serializer=game_dot_town__pb2.GetTownPresetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ck.game.TownService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ck.game.TownService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TownService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApproveConstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ApproveConstruction',
            game_dot_town__pb2.ApproveConstructionRequest.SerializeToString,
            game_dot_town__pb2.ApproveConstructionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstantCompleteConstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/InstantCompleteConstruction',
            game_dot_town__pb2.InstantCompleteConstructionRequest.SerializeToString,
            game_dot_town__pb2.InstantCompleteConstructionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccelerateConstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/AccelerateConstruction',
            game_dot_town__pb2.AccelerateConstructionRequest.SerializeToString,
            game_dot_town__pb2.AccelerateConstructionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandCraftQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ExpandCraftQueue',
            game_dot_town__pb2.ExpandCraftQueueRequest.SerializeToString,
            game_dot_town__pb2.ExpandCraftQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LevelUpStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/LevelUpStructure',
            game_dot_town__pb2.LevelUpStructureRequest.SerializeToString,
            game_dot_town__pb2.LevelUpStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SupplyConstructionMaterials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/SupplyConstructionMaterials',
            game_dot_town__pb2.SupplyConstructionMaterialsRequest.SerializeToString,
            game_dot_town__pb2.SupplyConstructionMaterialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DemolishStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/DemolishStructure',
            game_dot_town__pb2.DemolishStructureRequest.SerializeToString,
            game_dot_town__pb2.DemolishStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditTown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/EditTown',
            game_dot_town__pb2.EditTownRequest.SerializeToString,
            game_dot_town__pb2.EditTownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTownSegmentUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/StartTownSegmentUnlock',
            game_dot_town__pb2.StartTownSegmentUnlockRequest.SerializeToString,
            game_dot_town__pb2.StartTownSegmentUnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishTownSegmentUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/FinishTownSegmentUnlock',
            game_dot_town__pb2.FinishTownSegmentUnlockRequest.SerializeToString,
            game_dot_town__pb2.FinishTownSegmentUnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstantCompleteTownSegmentUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/InstantCompleteTownSegmentUnlock',
            game_dot_town__pb2.InstantCompleteTownSegmentUnlockRequest.SerializeToString,
            game_dot_town__pb2.InstantCompleteTownSegmentUnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccelerateTownSegmentUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/AccelerateTownSegmentUnlock',
            game_dot_town__pb2.AccelerateTownSegmentUnlockRequest.SerializeToString,
            game_dot_town__pb2.AccelerateTownSegmentUnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockBattleTownSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/UnlockBattleTownSegment',
            game_dot_town__pb2.UnlockBattleTownSegmentRequest.SerializeToString,
            game_dot_town__pb2.UnlockBattleTownSegmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveCumulativeAutoProductionsReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ReceiveCumulativeAutoProductionsReward',
            game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardRequest.SerializeToString,
            game_dot_town__pb2.ReceiveCumulativeAutoProductionsRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshFountainProductionReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/RefreshFountainProductionReward',
            game_dot_town__pb2.RefreshFountainProductionRewardRequest.SerializeToString,
            game_dot_town__pb2.RefreshFountainProductionRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveFountainProductionReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ReceiveFountainProductionReward',
            game_dot_town__pb2.ReceiveFountainProductionRewardRequest.SerializeToString,
            game_dot_town__pb2.ReceiveFountainProductionRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveLandmarkProductionReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ReceiveLandmarkProductionReward',
            game_dot_town__pb2.ReceiveLandmarkProductionRewardRequest.SerializeToString,
            game_dot_town__pb2.ReceiveLandmarkProductionRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAutoProductionCanActivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ChangeAutoProductionCanActivate',
            game_dot_town__pb2.ChangeAutoProductionCanActivateRequest.SerializeToString,
            game_dot_town__pb2.ChangeAutoProductionCanActivateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveTownPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/SaveTownPreset',
            game_dot_town__pb2.SaveTownPresetRequest.SerializeToString,
            game_dot_town__pb2.SaveTownPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadTownPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/LoadTownPreset',
            game_dot_town__pb2.LoadTownPresetRequest.SerializeToString,
            game_dot_town__pb2.LoadTownPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameTownPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/RenameTownPreset',
            game_dot_town__pb2.RenameTownPresetRequest.SerializeToString,
            game_dot_town__pb2.RenameTownPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTownPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/DeleteTownPreset',
            game_dot_town__pb2.DeleteTownPresetRequest.SerializeToString,
            game_dot_town__pb2.DeleteTownPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearTown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/ClearTown',
            game_dot_town__pb2.ClearTownRequest.SerializeToString,
            game_dot_town__pb2.ClearTownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpgradeTownPresetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/UpgradeTownPresetStorage',
            game_dot_town__pb2.UpgradeTownPresetStorageRequest.SerializeToString,
            game_dot_town__pb2.UpgradeTownPresetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStructureBookmarked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/SetStructureBookmarked',
            game_dot_town__pb2.SetStructureBookmarkedRequest.SerializeToString,
            game_dot_town__pb2.SetStructureBookmarkedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHouseIdsBookmarked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/SetHouseIdsBookmarked',
            game_dot_town__pb2.SetHouseIdsBookmarkedRequest.SerializeToString,
            game_dot_town__pb2.SetHouseIdsBookmarkedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockSkyGardenIsland(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/UnlockSkyGardenIsland',
            game_dot_town__pb2.UnlockSkyGardenIslandRequest.SerializeToString,
            game_dot_town__pb2.UnlockSkyGardenIslandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTownPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ck.game.TownService/GetTownPreset',
            game_dot_town__pb2.GetTownPresetRequest.SerializeToString,
            game_dot_town__pb2.GetTownPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
